### ISSUE TITLE
make install error: No rule to make target 'install-completion'

### ISSUE THREAD

**Issue by silkeh** [gopasspw/git-credential-gopass#3]
Running `make install` results in:

```
make: *** No rule to make target 'install-completion', needed by 'install'.  Stop.
```

Looks like the Makefile has a stray target [here](https://github.com/gopasspw/git-credential-gopass/blob/main/Makefile#L73):
```make
install: all install-completion
```

I have noticed the same for `gopass-hibp` and `gopass-summon-provider`.

**Comment by dominikschulz** [comment]
Thanks for reporting this. Looks like a left over from the split. Will clean this up.

**Comment by dominikschulz** [comment]
Fixed.
