### ISSUE TITLE
Add toolchain line in go.mod

### ISSUE THREAD

**Issue by ehaupt** [gopasspw/git-credential-gopass#72]
I ran into an issue updating the FreeBSD port of `git-credential-gopass` to `1.15.12`, related to Go 1.22's new way of handling the go.mod file for reproducibility. It now requires a toolchain line whenever it updates the `go.mod` file, as detailed here: https://go.dev/ref/mod#go-mod-file-toolchain.

Could you add this toolchain line to the project's go.mod? It would help avoid the 'no fetch' errors and make maintaining ports smoother.

**Comment by ehaupt** [comment]
Sorry, I just noticed 88d11d2. I'll patch the port to pull in this patch. Any chance you could tag a bugfix release?

**Comment by dominikschulz** [comment]
Sure, we can do that. But you could also send a PR. That might be faster.

**Comment by dominikschulz** [comment]
I have just tried this. `go mod tidy` removes the toolchain line if it matches the required Go version.

**Comment by ehaupt** [comment]
I suspect that 88d11d2b1b49f00b7fba9a917cf90f7ea14c9d1b solved the issue by setting the correct go minor version (`1.22.0` vs `1.22`). I've [patched](https://cgit.freebsd.org/ports/tree/security/git-credential-gopass/Makefile) the FreeBSD port to manually fetch the fixed `go.mod` version. I guess with the next tagged release we'll see.
