### ISSUE TITLE
How to use with sendmail?

### ISSUE THREAD

**Issue by ps245** [gopasspw/git-credential-gopass#73]
Hi'm wondering how to use this with [`git send-email`](https://git-send-email.io/). I read the [gitcredentials](https://git-scm.com/docs/gitcredentials) and [git-send-email](https://git-scm.com/docs/git-send-email) documents but still can't figure it out. Doesn't seem to be documented anywhere really either.

Found one entry on SO https://stackoverflow.com/questions/76117242 but am still confused what I am doing wrong.

```
[sendemail]
	smtpserver = example.com
	smtpuser = user@example.com
	smtpencryption = ssl
	smtpserverport = 465

[credential "smtp://example.com:465"]
	username = user@example.com
	helper = gopass -o mail/example_email
```

the issue seems to be that when i type:

```
git send-email --to="test@example.com" HEAD^
```

It still comes up with the prompt asking me to authenticate:

`Password for 'smtp://user@example.com@example.com:465'`

I do have the helper installed in my path:

```
$ git help -a | grep credential-
   credential-cache        Helper to temporarily store passwords in memory
   credential-store        Helper to store credentials on disk
   credential-gopass
```

**Comment by ps245** [comment]
@dominikschulz i signed up for the gopass slack, btw. if u could approve thanks.

**Comment by dngray** [comment]
You need to have:


```
[sendemail]
	smtpserver = example.com
	smtpuser = username <-- only the user name
	smtpencryption = ssl
	smtpserverport = 465

[credential "smtp://username@example.com:465"]
	helper = gopass
```

Then in your gopass store it must be in:

.../gopass/stores/root/git/example.com_465/username.gpg

This last part isn't documented anywhere that I can see.

**Comment by ps245** [comment]
Can confirm, this works!
